install:
  - sudo test/travis.setup-apt.sh
  - sudo apt-get update
  - sudo apt-get install --yes --force-yes build-essential wget mafft fasttree hmmer lua5.1 blast2 ncbi-blast+ unzip cpanminus mummer python-setuptools exonerate
  - sudo apt-get -t testing  --yes --force-yes install circos snap infernal
  - sudo test/travis.setup-augustus.sh
  - sudo test/travis.setup-gt.sh
  - sudo test/travis.setup-orthomcl.sh
  - sudo test/travis.setup-aragorn.sh
  - sudo test/travis.setup-gff3toembl.sh
  - sudo cpanm --force Carp Storable Bio::SearchIO List::Util Getopt::Long
  - curl -fsSL get.nextflow.io | bash
  - wget http://geneontology.org/ontology/go.obo
  - wget http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz
  - gunzip Pfam-A.hmm.gz && hmmpress Pfam-A.hmm && rm -f Pfam-A.hmm
cache:
  directories:
    - work
env:
  global:
    - ROOTDIR="$TRAVIS_BUILD_DIR"
script:
  - ./nextflow -c loc_travis.config -c params_default.config run annot.nf
