install:
  - sudo add-apt-repository ppa:debian-med/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install mafft
  - sudo test/travis.setup-apt.sh > /dev/null
  - sudo apt-get update -qq
  - sudo apt-get install --yes --force-yes circos build-essential wget fasttree hmmer lua5.1 blast2 ncbi-blast+ unzip cpanminus mummer python-setuptools exonerate
  - sudo apt-get -t testing  --yes --force-yes install snap infernal
  - sudo ln -s /usr/bin/fasttree /usr/bin/FastTree
  - sudo test/travis.setup-augustus.sh > /dev/null
  - sudo test/travis.setup-gt.sh > /dev/null
  - sudo test/travis.setup-orthomcl.sh > /dev/null
  - sudo test/travis.setup-aragorn.sh > /dev/null
  - sudo test/travis.setup-gff3toembl.sh > /dev/null
  - sudo cpanm --force Carp Storable Bio::SearchIO List::Util Getopt::Long
  - curl -fsSL get.nextflow.io | bash
  - wget -q http://geneontology.org/ontology/go.obo
  - wget -q http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz
  - gunzip Pfam-A.hmm.gz && hmmpress Pfam-A.hmm && rm -f Pfam-A.hmm
cache:
  directories:
    - work
env:
  global:
    - ROOTDIR="$TRAVIS_BUILD_DIR"
script:
  - cd test/testsuite
  - ./testsuite.rb -threads 2
  - cd ../..
  - ./nextflow -c loc_travis.config -c params_default.config run annot.nf -resume --do_circos=false